## Management 플러그인 활성화 및 포트 설정
management.tcp.port = 15672

## STOMP 플러그인 활성화 및 포트/자격증명 설정
stomp.tcp.port = 61613
stomp.default_user = guest
stomp.default_pass = guest

## RABBITMQ_ENABLED_PLUGINS 환경 변수 대체
plugins = rabbitmq_management, rabbitmq_stomp